---
kind: pipeline
type: kubernetes
name: default

steps:
  # - name: precheck
  #   image: orlandobrea/andes-check-image-exist:latest
  #   pull: always
  #   environment:
  #     # REGISTRY_URL: registry.hub.docker.com
  #     IMAGE_NAME: orlandobrea/dashboard-migracion-sips-fe
  #     TAG: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
  #     REGISTRY_USER:
  #       from_secret: REGISTRY_USER
  #     REGISTRY_PASSWORD:
  #       from_secret: REGISTRY_PASSWORD
  # Test

  - name: test
    image: node:12-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - npm install
      - npm run test

  # Release
  - name: release
    image: docker:dind
    # volumes:
    #   - name: dockersock
    #     path: /var/run
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - apk update && apk add git nodejs npm
      - npm install
      - npx semantic-release
      # - export GIT_HASH=$(git log -1 --format=format:"%H")
      - node -p "require('./package.json').version" | tr -d '\n' > .tags
      - echo ",${DRONE_BRANCH},${DRONE_BRANCH}-${DRONE_COMMIT_SHA},latest" | tr -d '\n' >> .tags
      - node -p "require('./package.json').version" | tr -d '\n' > .version_tag
      - echo "Tagged version "$(cat .tags)
  - name: build
    image: plugins/docker
    settings:
      debug: false
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      repo: orlandobrea/dashboard-migracion-sips-fe

  - name: gitops_release
    image: alpine/git
    commands:
      - apk update && apk add yq
      - git clone https://github.com/orlandobrea/gitops-kubernetes.git
      - cd gitops-kubernetes
      - git checkout $DRONE_BRANCH
      - echo "Actualizando version del deployment a "$(cat ../.version_tag)
      - cd dashboard_migration_sips
      - yq w -i values.yaml frontend.version $(cat ../../.version_tag)
      - git add values.yaml
      - git commit -m "release "$(cat ../../.version_tag)
      - git push origin $DRONE_BRANCH
